name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      # Build the Hugo site
      - name: Build Hugo site
        run: hugo --minify

      # Upload the public folder as an artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hugo-site
          path: public/
          overwrite: true

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Download the artifact
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: hugo-site

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
