name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      # Step 3: Build the Hugo site
      - name: Build Hugo site
        run: hugo --minify

      # Step 4: Upload artifact (Updated to v4)
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hugo-site
          path: public/
          overwrite: true

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Download artifact
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: hugo-site

      # Step 3: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
